---
- name: Install Docker
  hosts: aws1
  become: yes

  vars: 
    image_name: nginx
    container_name: nginx_container
    container_ports: 
      - "8080:80"
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present
      
  - name: Start NgDocker Service
    service: 
      name: docker
      state: started
      enabled: yes

  - name: Pull Image
    docker_image:
      name: "{{image_name}}"
      source: pull
  - name: run container
    docker_container:
      name: "{{container_name}}"
      image: "{{image_name}}"
      ports: "{{container_ports}}"
      state: started