apiVersion: v1
kind: Service
metadata:
  name: dep-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 ## Host Post 
      targetPort: 80 ## Container Port 
      nodePort: 30007

