services:

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  backend: 
    build: ./backend
    ports:
    - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  
  db:

    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    networks:
      - app-network

volumes:
  db-data: #Persistence Storage
networks:
  app-network: #Common network between all services